#pragma once
//from glfw3.h
#define KALUO_MOUSE_BUTTON_1         0
#define KALUO_MOUSE_BUTTON_2         1
#define KALUO_MOUSE_BUTTON_3         2
#define KALUO_MOUSE_BUTTON_4         3
#define KALUO_MOUSE_BUTTON_5         4
#define KALUO_MOUSE_BUTTON_6         5
#define KALUO_MOUSE_BUTTON_7         6
#define KALUO_MOUSE_BUTTON_8         7
#define KALUO_MOUSE_BUTTON_LAST      KALUO_MOUSE_BUTTON_8
#define KALUO_MOUSE_BUTTON_LEFT      KALUO_MOUSE_BUTTON_1
#define KALUO_MOUSE_BUTTON_RIGHT     KALUO_MOUSE_BUTTON_2
#define KALUO_MOUSE_BUTTON_MIDDLE    KALUO_MOUSE_BUTTON_3